import { ipcRenderer, contextBridge } from 'electron'
contextBridge.exposeInMainWorld('mainAPI', {
    loginSucceeded: async (session) => await ipcRenderer.invoke('login-succeeded', session),
    onGetCurrentUser: (callback) => ipcRenderer.on('get-current-user', callback),
    currentUser: (user) => ipcRenderer.send('current-user', user),
    onGoTo: (callback) => ipcRenderer.on('go-to', (_event, routePath) => callback(routePath)), 
    getRestBreathingDays: async (stage) => await ipcRenderer.invoke('get-rest-breathing-days', stage),
    getPacedBreathingDays: async (stage) => await ipcRenderer.invoke('get-paced-breathing-days', stage),
    getSegmentsAfterDate: async (date, stage) => await ipcRenderer.invoke('get-segments-after-date', date, stage),
    setStage: (stage) => ipcRenderer.invoke('set-stage', stage),
    showLoginWindow: () => ipcRenderer.send('show-login-window'),
    createLumosityView: (email, pw, userAgent) => ipcRenderer.send("create-lumosity-view", email, pw, userAgent),
    closeLumosityView: () => ipcRenderer.send('close-lumosity-view'),
    hideLumosityView: () => ipcRenderer.send('hide-lumosity-view'),
    showLumosityView: () => ipcRenderer.send('show-lumosity-view'),
    getLumosityDoneToday: () => ipcRenderer.invoke('get-lumosity-done-today'),
    setLumosityDoneToday: () => ipcRenderer.send('set-lumosity-done-today'),
    isStageComplete: async (stage) => await ipcRenderer.invoke('is-stage-complete', stage),
    pacerRegimeChanged: async (startTime, regime) => await ipcRenderer.invoke('pacer-regime-changed', startTime, regime),
    regimesForSession: async(condition, stage) => await ipcRenderer.invoke('regimes-for-session', condition, stage),
    uploadEmWaveData: async(session) => ipcRenderer.invoke('upload-emwave-data', session),
    uploadBreathData: async(session) => ipcRenderer.invoke('upload-breath-data', session),
    startPulseSensor: () => ipcRenderer.send('pulse-start'),
    stopPulseSensor: () => ipcRenderer.send('pulse-stop'),
    handleEmWaveIBIEvent: (callback) => ipcRenderer.on('emwave-ibi', callback),
    handleEmWaveStatusEvent: (callback) => ipcRenderer.on('emwave-status', callback),
    extractEmWaveSessionData: async (sinceDateTime, includeLiveIBI) => await ipcRenderer.invoke('emwave-extract-sessions', sinceDateTime, includeLiveIBI),
    getEmWaveSessionData: async (sessionIds) => await ipcRenderer.invoke('get-emwave-session-data', sessionIds),
    saveEmWaveSessionData: (emWaveSessionId, avgCoherence, pulseStartTime, validStatus, durationSec, stage) => ipcRenderer.invoke('save-emwave-session', emWaveSessionId, avgCoherence, pulseStartTime, validStatus, durationSec, stage),
    getEmWaveSessionsForStage: async (stage) => await ipcRenderer.invoke('get-emwave-sessions-for-stage', stage),
    getEmWaveSessionMinutesForDayAndStage: async(date, stage) => await ipcRenderer.invoke('get-emwave-session-minutes-for-day-and-stage', date, stage),
    hasDoneCognitiveExperiment: async(experiment, stage) => await ipcRenderer.invoke('has-done-cognitive-experiment', experiment, stage),
    latestExperimentResult: async(experiment, stage) => await ipcRenderer.invoke('latest-experiment-result', experiment, stage),
    saveCognitiveResults: (experiment, isRelevant, stage, data) => ipcRenderer.invoke('save-cognitive-results', experiment, isRelevant, stage, data),
    getKeyValue: async (key) => await ipcRenderer.invoke('get-key-value', key),
    setKeyValue: (key, value) => ipcRenderer.send('set-key-value', key, value),
    deleteKeyValue: (key) => ipcRenderer.send('delete-key-value', key),
    disableMenus: async () => ipcRenderer.invoke('disable-menus'),
    beep: async () => ipcRenderer.invoke('beep'),
    quit: () => ipcRenderer.invoke('quit'),
})
